### ISSUE TITLE
How to setExpression from json string.

### ISSUE THREAD

**Issue by Hirenp75** [magicops/JQuery-expression-builder#1]
Dear sir,

Recently i have try to implment the expression builder in our project.it's good jquery library.

**I need help for set Expression.**

**Example** : 
1) My variables list object like this
variables: [
        {
           variableId: "3fbae344-5254-410b-a250-04b73d45b5ea"
           name: "N1"
        },
        {
         variableId: "4723c9ad-d74a-4255-be7e-1fb8b287b9fb"
          name: "N2
        }
      ]

2) I have store the expression using expBuilder.getExpression() method in JSON object.

[3fbae344-5254-410b-a250-04b73d45b5ea]/[4723c9ad-d74a-4255-be7e-1fb8b287b9fb]

so,How to set Expression from above json in input expression textbox with name instead of variableId ?.

Please help me.

Thanks.

**Comment by magicops** [comment]
Hello,
Have you tried the code explained in the [plugin website](https://exp.js.org/demo.html#demo-variable) demo page?

Setting expression in current version doesn't work for none-digit variable ids. I will fix the issue as soon as possible.

In the meantime, you need to change your ids to digits.

**Comment by magicops** [comment]
I have fixed the issue and released the new version 2.1.2.
Check out the [CodePen](https://codepen.io/magicops/pen/yRgQwV/)
Thank you for using the tool.

**Comment by Hirenp75** [comment]
Dear sir,

Thanks for Update.

Thanks & Regards

Hiren Parejiya

9904079222
