### ISSUE TITLE
The getExpression function is stripping out parentheses

### ISSUE THREAD

**Issue by zo-ali** [magicops/JQuery-expression-builder#2]
Hi,

When inputting an expression with parentheses such as : (10+5)/2
The getExpression function removes the parentheses and returns: 10+5/2
However, the runExpression does work and respects the parentheses when evaluating the expression.

Tested here: https://exp.js.org/demo.html#demo-functions

Nice tool, Thanks!

**Comment by magicops** [comment]
The sum is in the expression tree and seems like it doesn't add the parentheses when is populating the output! I'll look into it and will get back to you soon.
Thank you for using the tool.

**Comment by magicops** [comment]
I have added parentheses to all BinaryNodes in the expression tree. It was calculating properly but not showing the parentheses in the toString function. I mark it as closed and please don't forget to give a start to the project. Thanks

**Comment by rharding98** [comment]
Hi,

I seem to be having this same issue using 2.1.1.
I am mainly using this to ensure what the user enters is valid.
(6-2)/2  getInput will return (6-2)/2 while getExpression returns 6-2/2

Any help would be appreciated.

Thanks,
Roy
