### ISSUE TITLE
Is Support Multiple Language ?

### ISSUE THREAD

**Issue by innodeltech** [magicops/JQuery-expression-builder#3]
Hi,

I Hope your doing well,

Recently, i use JQuery-expression-builder.js in our project.Everything work fine.but face some issue in other language (Like Hindi,Gujarati,etc) in library. 

how can i support multiple language in ExpressionBuilderVariable (variables) ?

is there any solution for multiple language if you have solution please let me know.

Thanks

**Comment by magicops** [comment]
Hi,
I'm glad you like the tool. I will add this functionality.

**Comment by magicops** [comment]
@innodeltech, I added a new property to the library to define your language characters like:

```
$('#txt').expressionBuilder({
    functions: funcs,
    variables: [
      {
        variableId: 1,
        name: 'Age'
      },
      {
        variableId: 2,
        name: 'Gender'
      }
    ],
    variableSpecialCharacters: ['ا', 'ب', 'پ', 'ت']
  });
```

**Comment by innodeltech** [comment]
Thanks for Quick Response.

**Comment by innodeltech** [comment]
Hi Please see my Multiple Language Options Object Values

English Language options values

expression: "Number1+Number2"
suggestions: "down"
variables:[{
	name: "Number1"
	variableId: "7bc365cc-58bf-4726-b422-8d5cfdaead6e"
},
{
	name: "Number2"
	variableId: "bbefe0f5-2edf-4a7d-a728-35b7f7b87c05"
}]

In English works fine.
-----------------------------------------------------------------
Gujarati Language Option Values

expression: "નંબર1+નંબર2"
suggestions: "down"
variables:[{
	name: "નંબર1"
	variableId: "2d39ef7f-e1ff-43f4-b880-c28fcdde7203"
},
{
	name: "નંબર2"
	variableId: "b5433b29-0c49-4f0b-a96f-56c582f3fe33"
}]

In Gujarati not working properly.(Expression not validate)

**Comment by magicops** [comment]
You should use "variableSpecialCharacters" option to introduce Gujarati characters:
```
$('#txt').expressionBuilder({
    functions: funcs,
    variables: [
      {
        variableId: 1,
        name: 'Age'
      },
      {
        variableId: 2,
        name: 'Gender'
      }
    ],
    variableSpecialCharacters: ['ا', 'ب', 'پ', 'ت']
  });
```
